name: Windows Build VS2026 BAT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-vs2026-bat:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run [Windows]build_vs2026.bat
        shell: cmd
        run: |
          call "[Windows]build_vs2026.bat"
          if errorlevel 1 exit /b %errorlevel%